Makefile
bazel/deps.bzl
buf/validate/internal/constraints.cc
buf/validate/internal/constraints.h

Bringing the `required` and `ignore_empty` constraints into conformance.
See bufbuild/protovalidate#115

Update required/ignore_empty behavior to match spec

---

.github/workflows/ci.yaml
.github/workflows/conformance.yaml
Makefile
bazel/deps.bzl
buf/validate/internal/extra_func.cc

See https://github.com/bufbuild/protovalidate/pull/164

Add string.host_and_port support

---

Makefile

Relatively minor issue: some targets directly invoke `bazel` instead of using the `$(BAZEL)` variable. The upshot of this is that e.g. `make BAZEL=bazelisk` does not work as expected as some calls will not use `bazelisk` as expected.

Makefile: fix bazel -> $(BAZEL) for some targets

---

.github/workflows/ci.yaml

Platform coverage in CI is valuable for C++ since the toolchains are so variable. This PR should ensure nobody accidentally breaks macOS support.
Windows does not currently work due to cel-cpp issues. I don't think we can put any priority on patching that right now. I think MSVC testing would go a long way to attest that changes are more properly portable, versus GCC and Clang which are fairly similar. Hopefully, we can eventually rectify this. The necessary workflow change is already present in this PR, so once `cel-cpp` is fixed we just need to add `windows-latest` to the matrix. Some day.
This PR is one I worked on a long time ago, but got stalled on. I rebased it and cleaned it up since I think it is valuable enough to merge.

Add macOS testing to CI

---

.bazelrc
.github/workflows/ci.yaml
.github/workflows/conformance.yaml
Makefile
WORKSPACE
bazel/cel_cpp.patch
bazel/deps.bzl
buf/validate/internal/constraints.cc
buf/validate/internal/constraints.h
buf/validate/internal/extra_func.cc
buf/validate/internal/field_rules.cc
buf/validate/validator.cc

Updates Protobuf to v27 and protovalidate to v0.7.1, and fixes all of the resulting compilation and conformance failures.
As one would expect, there was a tremendous amount of troubleshooting involved in this thankfully-relatively-small PR. Here's my log of what happened. I'll try to be succinct, but I want to capture all of the details so my reasoning can be understood in the future.
- First, I tried to update protobuf. This led to pulling a newer version of absl. The version of cel-cpp we use did not compile with this version of absl.
- Next, I tried to update cel-cpp. However, the latest version of cel-cpp is broken on macOS for two separate reasons <sup>[1](https://github.com/google/cel-cpp/issues/831), [2](https://github.com/google/cel-cpp/issues/832)</sup>.
- After taking a break to …

Editions fixes

---

Makefile
bazel/deps.bzl
buf/validate/conformance/runner.cc
buf/validate/conformance/runner.h
buf/validate/conformance/runner_main.cc
buf/validate/internal/BUILD.bazel
buf/validate/internal/cel_constraint_rules.cc
buf/validate/internal/cel_constraint_rules.h
buf/validate/internal/cel_rules.h
buf/validate/internal/constraint_rules.h
buf/validate/internal/constraints.cc
buf/validate/internal/constraints_test.cc
buf/validate/internal/field_rules.cc
buf/validate/internal/field_rules.h
buf/validate/internal/message_factory.cc
buf/validate/internal/message_factory.h
buf/validate/internal/message_rules.cc
buf/validate/internal/message_rules.h
buf/validate/validator.cc
buf/validate/validator.h

Like protovalidate-go and protovalidate-java, we need to adjust the code to handle dynamic descriptor sets more robustly, since we need to jump between resolving the protovalidate standard rules and the predefined rule extensions.  This necessitates adding a couple of additions to the API surface, namely `ValidatorFactory::SetMessageFactory` and `ValidatorFactory::SetAllowUnknownFields`, which controls instantiation of unknown dynamic types and whether or not to ignore unresolved rules, respectively. Like other protovalidate runtimes, we will default to failing compilation when unknown predefined rules are encountered. This should not break existing users but will prevent silent incorrect behavior.
TODO:
This will depend on https://github.com/bufbuild/protovalidate/pull/246.

Implement predefined field constraints

---

Makefile
bazel/deps.bzl
buf/validate/internal/cel_constraint_rules.cc
buf/validate/internal/cel_constraint_rules.h
buf/validate/internal/cel_rules.h
buf/validate/internal/constraint_rules.h
buf/validate/internal/constraints.cc
buf/validate/internal/constraints.h
buf/validate/internal/constraints_test.cc
buf/validate/internal/field_rules.cc
buf/validate/internal/message_rules.cc
buf/validate/validator.cc

Implements the changes needed to pass conformance after https://github.com/bufbuild/protovalidate/pull/265.
DO NOT MERGE until the following is done:

Implement structured field and rule paths for violations

---

buf/validate/conformance/runner.cc
buf/validate/internal/BUILD.bazel
buf/validate/internal/cel_constraint_rules.cc
buf/validate/internal/constraint_rules.h
buf/validate/internal/constraints.cc
buf/validate/internal/constraints.h
buf/validate/internal/constraints_test.cc
buf/validate/internal/proto_field.h
buf/validate/validator.cc
buf/validate/validator.h
buf/validate/validator_test.cc

Adds the ability to access the captured rule and field value from a Violation.
C++ protobuf doesn't really have a native "value" representation unlike other languages, so I've created a sort-of stand-in. The `ProtoField` class acts as a reference to a field on a message, and provides an interface to get a singular value as a `variant`. This should be good enough for most users, but users can also grab the information needed and use protobuf reflection directly instead if they have more complicated needs.
**This is a breaking change.** The API changes in the following ways:
- `Validator::Validate()` now returns the wrapper type `ValidationResult` instead of `Violations`. This can be converted into the protobuf `Violations` form using the `proto()` method.
- `ValidationResult.violations()` …

Add field and rule value to violations

---

Makefile
bazel/deps.bzl
buf/validate/internal/constraint_rules.h
buf/validate/internal/constraints.h
buf/validate/internal/field_rules.cc
buf/validate/validator.cc
buf/validate/validator_test.cc

Related protovalidate change: https://github.com/bufbuild/protovalidate/pull/297

Remove support for deprecated options

---

.bazelignore
.gitignore
Makefile
WORKSPACE
bazel/deps.bzl
bazel/json.bzl
bazel/shared_deps.json

In preparation for CMake support (#54), we need a system to share dependencies across build systems. To do this, a technique is needed which can work with both bzlmod and WORKSPACE mode, as well as CMake.
I have chosen to specify the dependency information in a JSON manifest. This manifest contains the necessary information to derive the sources for dependencies that are shared between build systems. For dependencies which are only needed for Bazel, such as rules repositories or dependencies of them, those will be specified in `deps.bzl` still. I don't think we will need any CMake-specific dependencies.
We may need to modify/extend this later for bzlmod support.

Implement shared dependencies system

---

.github/workflows/cmake.yaml
CMakeLists.txt
buf/validate/internal/extra_func.cc
buf/validate/internal/extra_func.h
cmake/Antlr4.cmake
cmake/Deps.cmake
cmake/MakePatchCommand.cmake
cmake/README.md
cmake/cel-cpp/CMakeLists.txt
deps/patches/cel_cpp/0004-Fix-build-on-Windows-MSVC.patch

- Antlr4 improvements: Jar download now checks hash, uses CACHE variables
- MakePatchCommand now tries to resolve the `patch` command ahead of time
- Add preliminary support for Windows

CMake cleanup and improvements

---

.bazelignore
.gitignore
CMakeLists.txt

This allows clangd to provide code intelligence. Most completions will work after configuration, although some completions (e.g. involving generated code) will require a build.
Generating a compile_commands.json file is non-trivial for Bazel so this should enable a better developer experience for people working on protovalidate-cc. Clangd can be used with a large variety of editors (Vim, Zed, Visual Studio Code, etc.)

CMake: Set up compile_commands.json automatically

---

buf/validate/internal/lib/ipv6.cc
buf/validate/internal/lib/uri.cc

In order to work around some edge cases with IPv6, I adopted a local state value that would ensure productions could only appear in specific states. However, the same problem is solved a bit more elegantly in https://github.com/bufbuild/protovalidate-go/pull/215 by simply always ensuring that the state after successfully consuming a production can't be invalid. This means that we need to handle the following edge cases:
- Before, we check that the dotted IP follows a separator or double colon; now we just check that the dotted IP production does not begin on a colon. This works because as long as there is no colon at the beginning, if we pass the dotted check, the only possible valid production is a dotted IP, and further checks prevent us from invalidly reaching this state without a …

Simplify IPv6 parsing logic a little

---

.bazelrc
MODULE.bazel
MODULE.bazel.lock
MODULE.bazel.tmpl
Makefile
bazel/deps.bzl
buf/validate/validator.cc

I've held off on adding more CI to this for now, we can tackle that when we tackle getting this on the BCR.
Note that cel-cpp is still not on the BCR; I'm not sure if this is a blocker for us getting on the BCR. Still, it should be possible for users to consume protovalidate-cc with bzlmod after this commit using `bazel_dep` + `archive_override` just like we're doing for cel-cpp.
Closes #66.

Initial bzlmod support

---

buf/validate/internal/BUILD.bazel
buf/validate/internal/cel_rules.h
buf/validate/internal/cel_validation_rules.cc
buf/validate/internal/cel_validation_rules.h
buf/validate/internal/field_rules.cc
buf/validate/internal/field_rules.h
buf/validate/internal/message_rules.cc
buf/validate/internal/message_rules.h
buf/validate/internal/rules.cc
buf/validate/internal/rules.h
buf/validate/internal/rules_test.cc
buf/validate/internal/validation_rules.h
buf/validate/validator.cc
buf/validate/validator.h
buf/validate/validator_test.cc
cmake/example/main.cc

Following the change from protovalidate v0.11.0 onward, the term "constraint" is now removed in places where it referred to protovalidate rules, using the following nomenclature:
- ConstraintRule -> ValidationRule
- Constraint -> Rule
etc.
This is an API breaking change, since names of public structures have changed.

Rename constraint -> rule globally

---

MODULE.bazel
MODULE.bazel.lock
deps/shared_deps.json

This updates protovalidate-cc to use the new v0.12.0 release of protovalidate.

Update to Protovalidate 0.12.0

---

MODULE.bazel
MODULE.bazel.lock
deps/shared_deps.json

This updates the repo to the v1.0.0-rc.1 release candidate for Protovalidate.

Update to pv release candidate

---

MODULE.bazel
MODULE.bazel.lock
MODULE.bazel.tmpl

Hurray, cel-cpp is now in the BCR as of a month ago. Let's get ourselves one step closer to the BCR by pulling from it. We don't need the Windows patch in Bazel since cel-cpp still doesn't work in Bazel on Windows anyways (maybe next release...)

Pull cel-cpp from the BCR

---

.github/workflows/publish-to-bcr.yaml
.github/workflows/release.yaml

Like I said... sorry for the noise. :) (Will try to balance around different people to bug for these small PRs.)
I almost hit publish before realizing that I failed to specify the BCR fork to publish using in thepublish workflow inputs.
Also, fix a race condition by ensuring that the release job does not run prior to the create-release-tag job.

Two more BCR fixes for v1.0.0-rc.2

---

.github/workflows/publish-to-bcr.yaml

Publish to BCR needs id-token + attestations.
Hopefully the last one?...

One more fix for BCR publish workflow

---

.github/workflows/release.yaml

Upstream merged my PR.
(This will also prevent future attestations from failing.)

Remove the workaround for creating a release draft

---

MODULE.bazel
MODULE.bazel.lock
buf/validate/internal/message_rules.cc
buf/validate/internal/rules.cc
buf/validate/internal/rules.h
deps/shared_deps.json

This implements https://github.com/bufbuild/protovalidate/pull/377.
(For this to land, the upstream PR must land first and be released, then we need to update the dependency here, then this PR should pass CI)

Implement MessageOneofRule

---

.github/workflows/release_prep.sh
README.md

For example,
https://github.com/bufbuild/protovalidate-cc/releases/tag/v1.0.0-rc.5 links to https://github.com/bufbuild/protovalidate-cc/releases/download/v1.0.0-rc.5/protovalidate-cc-v1.0.0-rc.5.tar.gz which 404s, but
https://github.com/bufbuild/protovalidate-cc/releases/download/v1.0.0-rc.5/protovalidate-cc-1.0.0-rc.5.tar.gz and
https://github.com/bufbuild/protovalidate-cc/archive/v1.0.0-rc.5.tar.gz are valid links.

Fix Bazel WORKSPACE instructions in readme and release message
